export const FA_TRANSLATIONS = {
    '@LogIn': 'ورود',
    '@LogOut': 'خروج',
    '@SignUp': 'ثبت نام',
    '@Welcome': 'خوش آمدید',
    '@Home': 'خانه',
    '@Profile': 'پروفایل',
    '@Settings': 'تنظیمات',
    '@RecipeBook' : 'کتاب آشپزی',
    '@Recipe': ' دستور پخت غذا',
    '@Manage': ' مدیریت ',
    '@SaveData': ' ثبت داد ها ',
    '@FetchData': ' به روز رسانی داد ها ',
    '@NewRecipe': 'اضافه کردن دستور غذای جدید + ',
    '@ManageRecipe': 'مدیریت دستور پخت',
    '@ToShoppingList': 'اضافه کردن به لیست خرید +',
    '@DeleteRecipe': 'حذف دستور پخت',
    '@EditRecipe': 'ویرایش دستور پخت',
    '@Ingredients': 'مواد مورد نیاز',
    '@IngredientName':'مواد مورد نیاز برای خرید',
    '@SelectRecipeFromListPls': 'لطفا یک دستور پخت غذا را از لیست انتخاب کنید ...',
    '@Save': 'ذخیره',
    '@Oil': 'روغن',
    '@Edit': 'ویرایش',
    '@Add': 'اضافه',
    '@Delete': 'حذف',
    '@Clear': 'پاک کردن',
    '@Amount': 'مقدار مورد نیاز ',
    '@Cancel': 'لغو',
    '@Name': 'نام غذا',
    '@ImageURL': 'آدرس عکس',
    '@Description': '  توضیحات',
    '@ShoppingList': 'لیست خرید ها'
  };